---
generic-service:
  nameOverride: hmpps-nomis-prisoner-api
  productId: DPS060

  replicaCount: 4

  poddisruptionbudget:
    enabled: true
    minAvailable: 3

  image:
    repository: ghcr.io/ministryofjustice/hmpps-nomis-prisoner-api
    tag: app_version    # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local    # override per environment
    tlsSecretName: hmpps-nomis-prisoner-api-cert
    modsecurity_enabled: true
    modsecurity_snippet: |
      SecRuleEngine On
      # team here grants access to the OpenSearch logs to delve into the cause of the blockage
      SecDefaultAction "phase:2,pass,log,tag:github_team=syscon-devs,tag:namespace={{ .Release.Namespace }}"
      # Default is only GET HEAD POST OPTIONS so need to include PUT etc.
      SecAction "id:900200,phase:1,nolog,pass,t:none,setvar:tx.allowed_methods=GET HEAD POST OPTIONS PUT PATCH DELETE,setvar:tx.paranoia_level=3"
      # attack-rce is 932 range
      SecRuleUpdateTargetByTag "attack-rce" "!ARGS:/.*comment/"
      # Block Detectify scanner with 418
      SecRule REQUEST_HEADERS:User-Agent "@pm detectify Detectify DETECTIFY" "id:800003,phase:1,deny,status:418,log,tag:github_team=syscon-devs,tag:namespace={{ .Release.Namespace }}"
      # Change default denial to be a 406 so that we can tell easily that it is modsecurity doing the blocking
      SecRuleUpdateActionById 949110 "t:none,deny,status:406,logdata:%{SERVER_NAME}"
      SecRuleUpdateActionById 959100 "t:none,deny,status:406,logdata:%{SERVER_NAME}"

  allowlist:
    groups:
      - internal

  # Environment variables to load into the deployment
  env:
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "oracle"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

  namespace_secrets:
    hmpps-nomis-prisoner-api-application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"
    hmpps-nomis-prisoner-api:
      JDBC_URL: "JDBC_URL"
      DB_USERNAME: "DB_USERNAME"
      DB_PASSWORD: "DB_PASSWORD"

  resources:
    requests:
      cpu: 10m
      memory: 640Mi
    limits:
      cpu: 2000m
      memory: 2048Mi

generic-prometheus-alerts:
  targetApplication: hmpps-nomis-prisoner-api
  alertSeverity: syscon
