---
generic-service:
  nameOverride: hmpps-nomis-prisoner-api

  replicaCount: 4

  image:
    repository: quay.io/hmpps/hmpps-nomis-prisoner-api
    tag: app_version    # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local    # override per environment
    tlsSecretName: hmpps-nomis-prisoner-api-cert

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "oracle"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

  namespace_secrets:
    hmpps-nomis-prisoner-api:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      JDBC_URL: "JDBC_URL"
      DB_USERNAME: "DB_USERNAME"
      DB_PASSWORD: "DB_PASSWORD"

  # Disabled for DSO AKS cluster
  allowlist: null

