---
generic-service:
  nameOverride: hmpps-nomis-prisoner-api
  productId: DPS060

  replicaCount: 4

  poddisruptionbudget:
    enabled: true
    minAvailable: 3

  image:
    repository: ghcr.io/ministryofjustice/hmpps-nomis-prisoner-api
    tag: app_version    # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local    # override per environment
    tlsSecretName: hmpps-nomis-prisoner-api-cert

  allowlist:
    groups:
      - internal

  # Environment variables to load into the deployment
  env:
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "oracle"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

  namespace_secrets:
    hmpps-nomis-prisoner-api-application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"
    hmpps-nomis-prisoner-api:
      JDBC_URL: "JDBC_URL"
      DB_USERNAME: "DB_USERNAME"
      DB_PASSWORD: "DB_PASSWORD"

  resources:
    requests:
      cpu: 10m
      memory: 640Mi
    limits:
      cpu: 2000m
      memory: 2048Mi

generic-prometheus-alerts:
  targetApplication: hmpps-nomis-prisoner-api
  alertSeverity: syscon
