---
# Per environment values which override defaults in hmpps-nomis-prisoner-api/values.yaml

generic-service:
  ingress:
    host: nomis-prisoner.aks-live-1.studio-hosting.service.justice.gov.uk

  env:
    API_BASE_URL_OAUTH: https://sign-in.hmpps.service.justice.gov.uk/auth
