# Per environment values which override defaults in hmpps-nomis-prisoner-api/values.yaml

generic-service:
  replicaCount: 4

  ingress:
    host: nomis-prisoner-api.prison.service.justice.gov.uk

  env:
    API_BASE_URL_HMPPS_AUTH: https://sign-in.hmpps.service.justice.gov.uk/auth
