CREATE OR REPLACE VIEW V_ADDRESSES
  (ADDRESS_ID,ADDRESS_TYPE,ADDRESS_TYPE_DESC,OWNER_CLASS,OWNER_ID,OWNER_SEQ,OWNER_CODE,START_DATE,END_DATE,ACTIVE_FLAG,FULL_ADDRESS,HOUSE,STREET,AREA,COUNTRY,FLAT,PREMISE,LOCALITY,CITY_CODE,CITY_NAME,COUNTY_CODE,PROV_STATE_CODE,POSTAL_CODE,COUNTRY_CODE,CAPACITY,COMMENT_TEXT,PRIMARY_FLAG,MAIL_FLAG,SERVICES_FLAG,NO_FIXED_ADDRESS_FLAG,SPECIAL_NEEDS,VALIDATED_FLAG,CONTACT_PERSON_NAME,BUSINESS_HOUR,COUNTY)
AS
select
  A.ADDRESS_ID
     ,A.ADDRESS_TYPE
--      ,substr(DECODE(A.address_type,NULL, NULL, OMS_MISCELLANEOUS.GETDESCCODE('ADDR_TYPE',A.address_type)),1,40)
     ,substr(DECODE(A.address_type,NULL, NULL, A.address_type),1,40)
     ,OWNER_CLASS
     ,OWNER_ID
     ,OWNER_SEQ
     ,OWNER_CODE
     ,A.start_date
     ,A.end_date
     ,DECODE(A.end_date, NULL, 'Y','N') ACTIVE_FLAG
     ,DECODE(NO_FIXED_ADDRESS_FLAG, 'Y', 'No fixed address',
             substr(DECODE(FLAT, NULL, NULL, FLAT||'  ')||DECODE(PREMISE, NULL, NULL, PREMISE||'  ')||
                    DECODE(STREET, NULL, NULL, STREET||'  ')||DECODE(LOCALITY, NULL, NULL, LOCALITY||'  ')||
--                     decode(city_name, NULL, OMS_MISCELLANEOUS.GETDESCCODE('CITY',CITY_CODE), city_name)||'  '||
                    decode(city_name, NULL, CITY_CODE, city_name)||'  '||
--                     DECODE(COUNTY_CODE,NULL, NULL, OMS_MISCELLANEOUS.GETDESCCODE('COUNTY',COUNTY_CODE)||'  '),1,200)||
                    DECODE(COUNTY_CODE,NULL, NULL, COUNTY_CODE||'  '),1,200)||
             DECODE(POSTAL_CODE, NULL, NULL, POSTAL_CODE||'  ')||
--              substr(DECODE(COUNTRY_CODE,NULL, NULL, OMS_MISCELLANEOUS.GETDESCCODE('COUNTRY',COUNTRY_CODE)),1,40) ) FULL_ADDRESS
             substr(DECODE(COUNTRY_CODE,NULL, NULL, COUNTRY_CODE),1,40) ) FULL_ADDRESS
     ,DECODE(NVL(NO_FIXED_ADDRESS_FLAG, 'N'), 'N',DECODE(FLAT, NULL, NULL, FLAT||'  ')||PREMISE, 'No fixed address') HOUSE
     ,DECODE(NVL(NO_FIXED_ADDRESS_FLAG, 'N'), 'N',DECODE(STREET, NULL, NULL, STREET), ' ') STREET
     ,DECODE(NVL(NO_FIXED_ADDRESS_FLAG, 'N'), 'N',
             substr(DECODE(LOCALITY, NULL, NULL, LOCALITY||'  ')||
--                     decode(city_name, NULL, OMS_MISCELLANEOUS.GETDESCCODE('CITY',CITY_CODE), city_name)||'  '||
                    decode(city_name, NULL, CITY_CODE, city_name)||'  '||
--                     DECODE(COUNTY_CODE,NULL, NULL, OMS_MISCELLANEOUS.GETDESCCODE('COUNTY',COUNTY_CODE)),1,80), ' ') AREA
                    DECODE(COUNTY_CODE,NULL, NULL, COUNTY_CODE),1,80), ' ') AREA
--      ,substr(DECODE(COUNTRY_CODE,NULL, NULL, OMS_MISCELLANEOUS.GETDESCCODE('COUNTRY',COUNTRY_CODE)),1,40) COUNTRY
     ,substr(DECODE(COUNTRY_CODE,NULL, NULL, COUNTRY_CODE),1,40) COUNTRY
     ,FLAT
     ,PREMISE
     ,LOCALITY
     ,CITY_CODE
--      ,substr(decode(city_name, NULL, OMS_MISCELLANEOUS.GETDESCCODE('CITY',CITY_CODE), city_name),1,40)
     ,substr(decode(city_name, NULL, CITY_CODE, city_name),1,40)
     ,COUNTY_CODE
     ,county_code
     ,POSTAL_CODE
     ,COUNTRY_CODE
     ,CAPACITY
     ,COMMENT_TEXT
     ,PRIMARY_FLAG
     ,MAIL_FLAG
     ,SERVICES_FLAG
     ,NO_FIXED_ADDRESS_FLAG
--      ,substr(DECODE(SPECIAL_NEEDS_CODE,NULL, NULL, OMS_MISCELLANEOUS.GETDESCCODE('PS_NEEDS',SPECIAL_NEEDS_CODE)),1,40)
     ,substr(DECODE(SPECIAL_NEEDS_CODE,NULL, NULL, SPECIAL_NEEDS_CODE),1,40)
     ,VALIDATED_PAF_flag
     ,CONTACT_PERSON_NAME
     ,BUSINESS_HOUR
--      ,OMS_MISCELLANEOUS.GETDESCCODE('COUNTY',COUNTY_CODE) COUNTY
     ,COUNTY_CODE COUNTY
FROM addresses a;