CREATE TABLE COURSE_ACTIVITY_AREAS
(
    CRS_ACTY_ID                   NUMBER(10, 0)                     NOT NULL,
    AREA_CODE                     VARCHAR2(12)                      NOT NULL,
    CREATE_DATETIME               TIMESTAMP    DEFAULT systimestamp NOT NULL,
    CREATE_USER_ID                VARCHAR2(32) DEFAULT USER         NOT NULL,
    MODIFY_DATETIME               TIMESTAMP                         NULL,
    MODIFY_USER_ID                VARCHAR2(32)                      NULL,
    AUDIT_TIMESTAMP               TIMESTAMP                         NULL,
    AUDIT_USER_ID                 VARCHAR2(32)                      NULL,
    AUDIT_MODULE_NAME             VARCHAR2(65)                      NULL,
    AUDIT_CLIENT_USER_ID          VARCHAR2(64)                      NULL,
    AUDIT_CLIENT_IP_ADDRESS       VARCHAR2(39)                      NULL,
    AUDIT_CLIENT_WORKSTATION_NAME VARCHAR2(64)                      NULL,
    AUDIT_ADDITIONAL_INFO         VARCHAR2(256)                     NULL,
    CONSTRAINT COURSE_ACTIVITY_AREAS_PK PRIMARY KEY (CRS_ACTY_ID, AREA_CODE),
    CONSTRAINT SYS_C0013339 CHECK ("CRS_ACTY_ID" IS NOT NULL),
    CONSTRAINT SYS_C0013340 CHECK ("AREA_CODE" IS NOT NULL),
--     CONSTRAINT SYS_C0013341 CHECK ("CREATE_DATETIME" IS NOT NULL),
--     CONSTRAINT SYS_C0013342 CHECK ("CREATE_USER_ID" IS NOT NULL),
    CONSTRAINT CSR_ACTY_AREA_CRS_ACTY_FK FOREIGN KEY (CRS_ACTY_ID) REFERENCES COURSE_ACTIVITIES (CRS_ACTY_ID)
);
CREATE UNIQUE INDEX COURSE_ACTIVITY_AREAS_PK ON COURSE_ACTIVITY_AREAS (CRS_ACTY_ID, AREA_CODE);