create view CASELOAD_CURRENT_ACCOUNTS
            (CASELOAD_ID, ACCOUNT_CODE, ACCOUNT_PERIOD_ID, CURRENT_BALANCE, BANK_ACCOUNT_TYPE, BANK_ACCOUNT_NUMBER,
             ACCOUNT_PARTY_TYPE, PAYEE_PERSON_ID, PAYEE_CORPORATE_ID, MODIFY_USER_ID, MODIFY_DATE, LIST_SEQ,
             ROUTING_NUMBER)
as
SELECT
 CCAB.CASELOAD_ID
, CCAB.ACCOUNT_CODE
, MAX(CCAT.ACCOUNT_PERIOD_ID)
, SUM(NVL(CCAT.CURRENT_BALANCE,0))
, CCAB.BANK_ACCOUNT_TYPE
, CCAB.BANK_ACCOUNT_NUMBER
, CCAB.ACCOUNT_PARTY_TYPE
, CCAB.PAYEE_PERSON_ID
, CCAB.PAYEE_CORPORATE_ID
, USER
, MAX(CCAT.MODIFY_DATE)
, MAX(CCAT.LIST_SEQ)
, CCAB.ROUTING_NUMBER
 FROM caseload_current_accounts_TXNS CCAT, caseload_current_accounts_base CCAB
 WHERE CCAT.caseload_id  = CCAB.caseload_id
 AND   CCAT.account_code  = CCAB.account_code
GROUP BY CCAB.CASELOAD_ID, CCAB.ACCOUNT_CODE,
	 CCAB.BANK_ACCOUNT_TYPE, CCAB.BANK_ACCOUNT_NUMBER, CCAB.ACCOUNT_PARTY_TYPE,
	 CCAB.PAYEE_PERSON_ID, CCAB.PAYEE_CORPORATE_ID, CCAB.ROUTING_NUMBER
;


