CREATE TABLE "OFFENDER_MOVEMENT_APPS_MULTI"
(
  "OFF_MOVEMENT_APPS_MULTI_ID" NUMBER(10,0) NOT NULL
    CONSTRAINT "OFF_MOVEMENT_APPS_MULTI_PK" PRIMARY KEY,
  "OFFENDER_MOVEMENT_APP_ID" NUMBER(10,0) NOT NULL,
  "TAP_ABS_TYPE" VARCHAR2(12),
  "TAP_ABS_SUBTYPE" VARCHAR2(12),
  "EVENT_SUB_TYPE" VARCHAR2(12) NOT NULL,
  "FROM_DATE" DATE NOT NULL,
  "RELEASE_TIME" DATE NOT NULL,
  "TO_DATE" DATE NOT NULL,
  "RETURN_TIME" DATE NOT NULL,
  "COMMENT_TEXT" VARCHAR2(4000),
  "TO_ADDRESS_OWNER_CLASS" VARCHAR2(12),
  "TO_ADDRESS_ID" NUMBER(10,0),
  "TO_AGY_LOC_ID" VARCHAR2(6),
  "CONTACT_PERSON_NAME" VARCHAR2(40),
  "CREATE_DATETIME" TIMESTAMP DEFAULT systimestamp NOT NULL,
  "CREATE_USER_ID" VARCHAR2(32) DEFAULT USER NOT NULL,
  "MODIFY_DATETIME" TIMESTAMP,
  "MODIFY_USER_ID" VARCHAR2(32),
  "AUDIT_TIMESTAMP" TIMESTAMP,
  "AUDIT_USER_ID" VARCHAR2(32),
  "AUDIT_MODULE_NAME" VARCHAR2(65),
  "AUDIT_CLIENT_USER_ID" VARCHAR2(64),
  "AUDIT_CLIENT_IP_ADDRESS" VARCHAR2(39),
  "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64),
  "AUDIT_ADDITIONAL_INFO" VARCHAR2(256),
  CONSTRAINT "OFF_MOVEMENT_APPS_MULTI_FK" FOREIGN KEY ("OFFENDER_MOVEMENT_APP_ID") REFERENCES "OFFENDER_MOVEMENT_APPS" ("OFFENDER_MOVEMENT_APP_ID")
);

CREATE INDEX "OFF_MOVEMENT_APPS_MULTI_FK" ON "OFFENDER_MOVEMENT_APPS_MULTI" ("OFFENDER_MOVEMENT_APP_ID");


