CREATE TABLE OFFENDER_PROFILES
(
    OFFENDER_BOOK_ID NUMBER(10,0) NOT NULL,
    PROFILE_SEQ NUMBER(6,0) NOT NULL,
    CHECK_DATE DATE NOT NULL ,
    MODIFY_USER_ID VARCHAR2(32),
    CREATE_DATETIME TIMESTAMP DEFAULT systimestamp NOT NULL ,
    CREATE_USER_ID VARCHAR2(32) DEFAULT USER NOT NULL ,
    MODIFY_DATETIME TIMESTAMP,
    AUDIT_TIMESTAMP TIMESTAMP,
    AUDIT_USER_ID VARCHAR2(32),
    AUDIT_MODULE_NAME VARCHAR2(65),
    AUDIT_CLIENT_USER_ID VARCHAR2(64),
    AUDIT_CLIENT_IP_ADDRESS VARCHAR2(39),
    AUDIT_CLIENT_WORKSTATION_NAME VARCHAR2(64),
    AUDIT_ADDITIONAL_INFO VARCHAR2(256),
    CONSTRAINT OFFENDER_PROFILES_PK PRIMARY KEY (OFFENDER_BOOK_ID,PROFILE_SEQ),
    CONSTRAINT OFF_PFL_OFF_BKG_F1 FOREIGN KEY (OFFENDER_BOOK_ID) REFERENCES OFFENDER_BOOKINGS(OFFENDER_BOOK_ID)
);
CREATE UNIQUE INDEX OFFENDER_PROFILES_PK ON OFFENDER_PROFILES (OFFENDER_BOOK_ID,PROFILE_SEQ);

