CREATE TABLE COURSE_SCHEDULE_RULES (
    COURSE_SCHEDULE_RULE_ID	NUMBER(10,0)  NOT NULL		        ,
    CRS_ACTY_ID	NUMBER(10,0)              NOT NULL		        ,
    WEEK_NO	NUMBER(3,0)	     ,
    MONDAY_FLAG	VARCHAR2(1 CHAR)	      NOT NULL	DEFAULT 'N' ,
    TUESDAY_FLAG	VARCHAR2(1 CHAR)      NOT NULL	DEFAULT 'N' ,
    WEDNESDAY_FLAG	VARCHAR2(1 CHAR)      NOT NULL	DEFAULT 'N' ,
    THURSDAY_FLAG	VARCHAR2(1 CHAR)      NOT NULL	DEFAULT 'N' ,
    FRIDAY_FLAG	VARCHAR2(1 CHAR)	      NOT NULL	DEFAULT 'N' ,
    SATURDAY_FLAG	VARCHAR2(1 CHAR)	  NOT NULL	DEFAULT 'N' ,
    SUNDAY_FLAG	VARCHAR2(1 CHAR)	      NOT NULL	DEFAULT 'N' ,
    START_TIME	DATE	                  NOT NULL	,
    END_TIME	DATE,
    CREATE_DATETIME	TIMESTAMP(9)	      NOT NULL	DEFAULT systimestamp,
    CREATE_USER_ID	VARCHAR2(32 CHAR)	  NOT NULL	DEFAULT USER 	,
    MODIFY_DATETIME	TIMESTAMP(9)	 ,
    MODIFY_USER_ID	VARCHAR2(32 CHAR),
    AUDIT_TIMESTAMP	TIMESTAMP(9)	 ,
    AUDIT_USER_ID	VARCHAR2(32 CHAR),
    AUDIT_MODULE_NAME	VARCHAR2(65 CHAR)	 ,
    AUDIT_CLIENT_USER_ID	VARCHAR2(64 CHAR),
    AUDIT_CLIENT_IP_ADDRESS	VARCHAR2(39 CHAR),
    AUDIT_CLIENT_WORKSTATION_NAME	VARCHAR2(64 CHAR),
    AUDIT_ADDITIONAL_INFO	VARCHAR2(256 CHAR),
    SLOT_CATEGORY_CODE	VARCHAR2(12 CHAR)	,
    CONSTRAINT COURSE_SCHEDULE_RULES_PK PRIMARY KEY (COURSE_SCHEDULE_RULE_ID),
    CONSTRAINT CRS_SCH_RULE_CRS_ACTY_FK FOREIGN KEY (CRS_ACTY_ID)  REFERENCES COURSE_ACTIVITIES (CRS_ACTY_ID)
);

--CREATE INDEX COURSE_SCHEDULE_RULES_NI1 ON COURSE_SCHEDULE_RULES (CRS_ACTY_ID);

--OMS_OWNER	COURSE_SCHEDULE_RULES_PK	UNIQUE  	VALID	NORMAL	N	NO		NO	COURSE_SCHEDULE_RULE_ID
--OMS_OWNER	COURSE_SCHEDULE_RULES_NI1	NONUNIQUE	VALID	NORMAL	N	NO		NO	CRS_ACTY_ID
--
--COURSE_SCHEDULE_RULES_PK Primary_Key		   				                                                    ENABLED	NOT DEFERRABLE	VALIDATED	USER NAME			18-APR-17	OMS_OWNER	COURSE_SCHEDULE_RULES_PK
--CRS_SCH_RULE_CRS_ACTY_FK Foreign_Key		OMS_OWNER	COURSE_ACTIVITIES	COURSE_ACTIVITIES_PK	NO ACTION	ENABLED	NOT DEFERRABLE	VALIDATED	USER NAME			18-APR-17
