CREATE TABLE PROFILE_TYPES (
    PROFILE_TYPE VARCHAR2(12) NOT NULL PRIMARY KEY ,
    PROFILE_CATEGORY VARCHAR2(12),
    DESCRIPTION VARCHAR2(40),
    LIST_SEQ NUMBER(6,0) NOT NULL,
    MANDATORY_FLAG VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    UPDATED_ALLOWED_FLAG VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    CODE_VALUE_TYPE VARCHAR2(12) NOT NULL,
    ACTIVE_FLAG VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    EXPIRY_DATE DATE,
    MODIFY_USER_ID VARCHAR2(32),
    MODIFIED_DATE DATE NOT NULL,
    CREATE_DATETIME TIMESTAMP DEFAULT systimestamp NOT NULL,
    CREATE_USER_ID VARCHAR2(32) DEFAULT USER NOT NULL,
    MODIFY_DATETIME TIMESTAMP,
    AUDIT_TIMESTAMP TIMESTAMP,
    AUDIT_USER_ID VARCHAR2(32),
    AUDIT_MODULE_NAME VARCHAR2(65),
    AUDIT_CLIENT_USER_ID VARCHAR2(64),
    AUDIT_CLIENT_IP_ADDRESS VARCHAR2(39),
    AUDIT_CLIENT_WORKSTATION_NAME VARCHAR2(64),
    AUDIT_ADDITIONAL_INFO VARCHAR2(256)
);
CREATE UNIQUE INDEX PROFILE_TYPES_PK ON PROFILE_TYPES (PROFILE_TYPE);