CREATE TABLE OFFENDER_PHYSICAL_ATTRIBUTES (
    OFFENDER_BOOK_ID                    NUMBER(10,0)                    NOT NULL,
    ATTRIBUTE_SEQ                       NUMBER(6,0)                     NOT NULL,
    HEIGHT_FT                           NUMBER(6,0),
    HEIGHT_IN                           NUMBER(6,0),
    HEIGHT_CM                           NUMBER(6,0),
    WEIGHT_LBS                          NUMBER(6,0),
    WEIGHT_KG                           NUMBER(6,0),
    CREATE_DATETIME                     TIMESTAMP DEFAULT systimestamp  NOT NULL,
    CREATE_USER_ID                      VARCHAR2(32) DEFAULT USER       NOT NULL,
    MODIFY_DATETIME                     TIMESTAMP,
    MODIFY_USER_ID                      VARCHAR2(32),
    AUDIT_TIMESTAMP                     TIMESTAMP,
    AUDIT_USER_ID                       VARCHAR2(32),
    AUDIT_MODULE_NAME                   VARCHAR2(65),
    AUDIT_CLIENT_USER_ID                VARCHAR2(64),
    AUDIT_CLIENT_IP_ADDRESS             VARCHAR2(39),
    AUDIT_CLIENT_WORKSTATION_NAME       VARCHAR2(64),
    AUDIT_ADDITIONAL_INFO               VARCHAR2(256),
    CONSTRAINT OFFENDER_PHYSICAL_ATTRIBUTE_PK PRIMARY KEY (OFFENDER_BOOK_ID,ATTRIBUTE_SEQ),
    CONSTRAINT OFF_PHYSICAL_ATTRIBUTES_FK9 FOREIGN KEY (OFFENDER_BOOK_ID)
    REFERENCES OFFENDER_BOOKINGS(OFFENDER_BOOK_ID)
);
CREATE UNIQUE INDEX OFFENDER_PHYSICAL_ATTRIBUTE_PK ON OFFENDER_PHYSICAL_ATTRIBUTES (OFFENDER_BOOK_ID,ATTRIBUTE_SEQ);